import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { classNames } from "@/lib/helpers";
import InfoBar from "@/components/info-bar";
import Sidebar from "@/components/sidebar";
import StoreProvider from "@/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Frontend Final Test - Tailwind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={inter.className}>
          <div className={classNames("h-screen overflow-hidden bg-white")}>
            <InfoBar />

            <Sidebar />

            {children}
          </div>
        </body>
      </StoreProvider>
    </html>
  );
}
