import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { classNames } from "@/lib/helpers";
import InfoBar from "@/components/info-bar";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Frontend Final Test - Tailwind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={classNames("h-screen overflow-hidden bg-white")}>
          <InfoBar />

          <div className="relative mt-20 flex">
            <Sidebar />
            <div className="flex-1 p-6">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
